---
title: "Longitudinal Modelling Examples"
output: html_notebook
---

```{r setup, include = FALSE}

knitr::opts_chunk$set(warning = FALSE, message = FALSE)

# Load packages
library(readxl)
library(tidyverse)
library(ggplot2)
library(reshape2)
library(glmmTMB)
library(lqmm)
library(MASS)
library(DHARMa)
options(scipen = 999)

# Read in group data

groupA = read_xlsx("data/groupAinfantsData_AD_23Feb2023.xlsx")
varA = colnames(groupA[, 17:56])

groupB = read_xlsx("data/groupBinfantsData_AD_23Feb2023.xlsx")
varB = colnames(groupB[, 16:34])

# Change variable names

## Study design and covariates

colnames(groupA)[1:4] = c("ID", "Group", "Time", "Treatment")
groupA$Time = as.factor(groupA$Time)
colnames(groupA)[10] = c("QFT")
colnames(groupA)[12:13] = c("Feeding", "Antibiotic")

colnames(groupB)[1:4] =  c("ID", "Group", "Time", "Treatment")
groupB$Time = as.factor(groupB$Time)
colnames(groupB)[10] = c("QFT")
colnames(groupB)[12:13] = c("Feeding", "Antibiotic")

# Create new dummy variables for feeding and antibiotic

groupA$FA = ifelse(groupA$Feeding == "Breast Milk" & groupA$Antibiotic == "Yes", 3, ifelse(groupA$Feeding == "Breast Milk" & groupA$Antibiotic == "No", 2, ifelse(groupA$Feeding == "Formula" & groupA$Antibiotic == "No", 1, 0)))
groupA$FA = factor(groupA$FA)

groupB$FA = ifelse(groupB$Feeding == "Breast Milk" & groupB$Antibiotic == "Y", 3, ifelse(groupB$Feeding == "Breast Milk" & groupB$Antibiotic == "N", 2, ifelse(groupB$Feeding == "Formula" & groupB$Antibiotic == "N", 1, 0)))
groupB$FA = factor(groupB$FA)

## Create immune response data sets

# Rename by number

groupA = rename_with(.data = groupA, .fn = ~ paste0("O", 1:length(varA)), .cols = 17:56)
groupB = rename_with(.data = groupB, .fn = ~ paste0("O", 1:length(varB)), .cols = 16:34)

# Drop indeterminate QFT observations
indet_idsA = groupA[which(groupA$QFT == "Indeterminate"), ]$ID
indet_idsB = groupB[which(groupB$QFT == "Indeterminate"), ]$ID

groupA = groupA[-which(groupA$ID %in% indet_idsA), ]
groupB = groupB[-which(groupB$ID %in% indet_idsB), ]

# Labels and labeller function for plotting

groupnames = list(
  '0'="Formula & Cotrimoxazole",
  '1'="Formula & No Cotrimoxazole",
  '2'="Breastfeeding & No Cotrimoxazole",
  '3'="Breastfeeding & Cotrimoxazole"
)

labeller = function(variable,value){
  return(groupnames[value])
}

```

**%CD4+ totIL22+**: 
```{r Outcome6, include=TRUE}
l = varA[6]
k = 6

# Fit models

# LMM

AM_0.1 = glmmTMB(O6 ~ Treatment*Time + Gender*Time + (1| ID), data = groupA, family = gaussian(link = "identity"))
AS_0.1 = summary(AM_0.1)

R0.1 = ranef(AM_0.1)
qqnorm(R0.1$cond$ID$`(Intercept)`, main = "")
qqline(R0.1$cond$ID$`(Intercept)`)

Rs0.1 = residuals(AM_0.1, type = "response")
qqnorm(Rs0.1, main = "")
qqline(Rs0.1)

AM_0.2 = glmmTMB(O6 ~ QFT*Time + Gender*Time + (1| ID), data = groupA, family = gaussian(link = "identity"))
AS_0.2 = summary(AM_0.2)

R0.2 = ranef(AM_0.2)
qqnorm(R0.2$cond$ID$`(Intercept)`, main = "")
qqline(R0.2$cond$ID$`(Intercept)`)

Rs0.2 = residuals(AM_0.2, type = "response")
qqnorm(Rs0.2, main = "")
qqline(Rs0.2)

# Formula, antibiotic is ref for breastfeeding, antibiotic (3)
# Formula, antibiotic is ref for formula, no antibiotic (1)

AM_0.3 = glmmTMB(O6 ~ FA*Time + Gender*Time + (1| ID), data = groupA, family = gaussian(link = "identity"))
AS_0.3 = summary(AM_0.3)

R0.3 = ranef(AM_0.3)
qqnorm(R0.3$cond$ID$`(Intercept)`, main = "")
qqline(R0.3$cond$ID$`(Intercept)`)

Rs0.3 = residuals(AM_0.3, type = "response")
qqnorm(Rs0.3, main = "")
qqline(Rs0.3)

# GLMM

AM_1.1 = glmmTMB(O6 ~ Treatment*Time + Gender*Time + (1| ID), data = groupA, family = Gamma(link = "log"))
AS_1.1 = summary(AM_1.1)

R1.1 = ranef(AM_1.1)
qqnorm(R1.1$cond$ID$`(Intercept)`, main = "")
qqline(R1.1$cond$ID$`(Intercept)`)

plot(simulateResiduals(AM_1.1, n = 1000))

# Treatment

pred_v1frame = AM_1.1$frame

pred_v1 = predict(AM_1.1, type = "cond")
pred_v1dat = data.frame(ID = pred_v1frame$ID, Time = as.character(pred_v1frame$Time), 
                        MVA85A = as.character(pred_v1frame$Treatment),
                        Sex = as.character(pred_v1frame$Gender), O = pred_v1frame$O6, P = pred_v1)


mean_by_v1_pred = pred_v1dat %>% group_by(Time, MVA85A) %>%
  summarise(meanP = mean(P, na.rm = TRUE), seP = 0, .groups = 'drop')
mean_by_v1_observed = pred_v1dat %>% group_by(Time, MVA85A) %>%
  summarise(meanO = mean(O, na.rm = TRUE), seO = sd(O) / sqrt(n()), .groups = 'drop')

mean_by_v1_predG = pred_v1dat %>% group_by(Time, Sex, MVA85A) %>%
  summarise(meanP = mean(P, na.rm = TRUE), seP = 0, .groups = 'drop')
mean_by_v1_observedG = pred_v1dat %>% group_by(Time, Sex, MVA85A) %>%
  summarise(meanO = mean(O, na.rm = TRUE), seO = sd(O) / sqrt(n()), .groups = 'drop')


meanvec = c(mean_by_v1_pred$meanP, mean_by_v1_observed$meanO)
statusvec = c(rep("Predicted", 6), rep("Observed", 6))
sevec = c(mean_by_v1_pred$seP, mean_by_v1_observed$seO)
daysvec = c(mean_by_v1_pred$Time, mean_by_v1_observed$Time)
varvec = c(mean_by_v1_pred$MVA85A, mean_by_v1_observed$MVA85A)

v1df = data.frame(Status = statusvec, Time = daysvec, Mean = meanvec, SEL = meanvec - sevec, SEU = meanvec + sevec, Variable = varvec)
v1df$Time = factor(v1df$Time, levels = c("56", "112", "365"))

ggplot(v1df, aes(x = Time, y = Mean, color = factor(Variable), linetype = Status)) +
  ylim(0, 0.2) +
  geom_point(aes(x = Time, y = Mean, color = factor(Variable))) +
  geom_line(aes(x = Time, y = Mean, color = factor(Variable), group = interaction(Variable, Status)), linewidth = 0.8) +
  scale_colour_manual(name = "Priming", labels = c("Control", "MVA85A"),
                      breaks = c("Control", "MVA85A"),
                      values = c("orange", "firebrick")) +
  scale_linetype_manual(name = "Mean",
                        values = c("Observed" = "solid", "Predicted" = "dashed"),  # Define line types for each level of Status
                        labels = c("Observed" = "Empirical", "Predicted" = "Conditional (GLMM Prediction)")) +  # Set custom labels
  #values = c("Control" = "darkslategrey", "MVA85A" = "firebrick")) +  # Adjust colors for clarity
  theme_bw() + xlab("\n Time (Days After Birth)") + ylab(paste0("Mean ", varA[6], " \n")) + labs(title = "") + 
  theme(axis.title.x = element_text(size = 12, family = "Arial", face = "bold"),
        axis.title.y = element_text(size = 12, family = "Arial", face = "bold"),
        axis.text.x = element_text(size = 10, family = "Arial"),
        axis.text.y = element_text(size = 10, family = "Arial"),
        legend.text = element_text(size = 10, family = "Arial"),
        legend.position = "bottom")

AM_1.2 = glmmTMB(O6 ~ QFT*Time + Gender*Time + (1| ID), data = groupA, family = Gamma(link = "log"))
AS_1.2 = summary(AM_1.2)

R1.2 = ranef(AM_1.2)
qqnorm(R1.2$cond$ID$`(Intercept)`, main = "")
qqline(R1.2$cond$ID$`(Intercept)`)

plot(simulateResiduals(AM_1.2, n = 1000))

# QFT

pred_v2frame = AM_1.2$frame

pred_v2 = predict(AM_1.2, type = "cond")
pred_v2dat = data.frame(ID = pred_v2frame$ID, Time = as.character(pred_v2frame$Time), 
                        QFT = as.character(pred_v2frame$QFT),
                        Sex = as.character(pred_v2frame$Gender), O = pred_v2frame$O6, P = pred_v2)


mean_by_v2_pred = pred_v2dat %>% group_by(Time, QFT) %>%
  summarise(meanP = mean(P, na.rm = TRUE), seP = 0, .groups = 'drop')
mean_by_v2_observed = pred_v2dat %>% group_by(Time, QFT) %>%
  summarise(meanO = mean(O, na.rm = TRUE), seO = sd(O) / sqrt(n()), .groups = 'drop')

mean_by_v2_predG = pred_v2dat %>% group_by(Time, Sex, QFT) %>%
  summarise(meanP = mean(P, na.rm = TRUE), seP = 0, .groups = 'drop')
mean_by_v2_observedG = pred_v2dat %>% group_by(Time, Sex, QFT) %>%
  summarise(meanO = mean(O, na.rm = TRUE), seO = sd(O) / sqrt(n()), .groups = 'drop')


meanvec = c(mean_by_v2_pred$meanP, mean_by_v2_observed$meanO)
statusvec = c(rep("Predicted", 6), rep("Observed", 6))
sevec = c(mean_by_v2_pred$seP, mean_by_v2_observed$seO)
daysvec = c(mean_by_v2_pred$Time, mean_by_v2_observed$Time)
varvec = c(mean_by_v2_pred$QFT, mean_by_v2_observed$QFT)

v2df = data.frame(Status = statusvec, Time = daysvec, Mean = meanvec, SEL = meanvec - sevec, SEU = meanvec + sevec, Variable = varvec)
v2df$Time = factor(v2df$Time, levels = c("56", "112", "365"))

ggplot(v2df, aes(x = Time, y = Mean, color = factor(Variable), linetype = Status)) +
  ylim(0, 0.2) +
  geom_point(aes(x = Time, y = Mean, color = factor(Variable))) +
  geom_line(aes(x = Time, y = Mean, color = factor(Variable), group = interaction(Variable, Status)), linewidth = 0.8) +
  scale_colour_manual(name = "Maternal QFT", labels = c("Negative", "Positive"),
                      breaks = c("Negative", "Positive"),
                      values = c("darkcyan", "darkblue")) +
  scale_linetype_manual(name = "Mean",
                        values = c("Observed" = "solid", "Predicted" = "dashed"),  # Define line types for each level of Status
                        labels = c("Observed" = "Empirical", "Predicted" = "Conditional (GLMM Prediction)")) +  # Set custom labels
  #values = c("Control" = "darkslategrey", "MVA85A" = "firebrick")) +  # Adjust colors for clarity
  theme_bw() + xlab("\n Time (Days After Birth)") + ylab(paste0("Mean ", varA[6], " \n")) + labs(title = "") + 
  theme(axis.title.x = element_text(size = 12, family = "Arial", face = "bold"),
        axis.title.y = element_text(size = 12, family = "Arial", face = "bold"),
        axis.text.x = element_text(size = 10, family = "Arial"),
        axis.text.y = element_text(size = 10, family = "Arial"),
        legend.text = element_text(size = 10, family = "Arial"),
        legend.position = "bottom")

AM_1.3 = glmmTMB(O6 ~ FA*Time + Gender*Time + (1| ID), data = groupA, family = Gamma(link = "log"))
AS_1.3 = summary(AM_1.3)

R1.3 = ranef(AM_1.3)
qqnorm(R1.3$cond$ID$`(Intercept)`, main = "")
qqline(R1.3$cond$ID$`(Intercept)`)

plot(simulateResiduals(AM_1.3, n = 1000))

# FA

pred_v3frame = AM_1.3$frame

pred_v3 = predict(AM_1.3, type = "cond")
pred_v3dat = data.frame(ID = pred_v3frame$ID, Time = as.character(pred_v3frame$Time), 
                        FA = as.character(pred_v3frame$FA),
                        Sex = as.character(pred_v3frame$Gender), O = pred_v3frame$O6, P = pred_v3)


mean_by_v3_pred = pred_v3dat %>% group_by(Time, FA) %>%
  summarise(meanP = mean(P, na.rm = TRUE), seP = 0, .groups = 'drop')
mean_by_v3_observed = pred_v3dat %>% group_by(Time, FA) %>%
  summarise(meanO = mean(O, na.rm = TRUE), seO = sd(O) / sqrt(n()), .groups = 'drop')

mean_by_v3_predG = pred_v3dat %>% group_by(Time, Sex, FA) %>%
  summarise(meanP = mean(P, na.rm = TRUE), seP = 0, .groups = 'drop')
mean_by_v3_observedG = pred_v3dat %>% group_by(Time, Sex, FA) %>%
  summarise(meanO = mean(O, na.rm = TRUE), seO = sd(O) / sqrt(n()), .groups = 'drop')


meanvec = c(mean_by_v3_pred$meanP, mean_by_v3_observed$meanO)
statusvec = c(rep("Predicted", 12), rep("Observed", 12))
sevec = c(mean_by_v3_pred$seP, mean_by_v3_observed$seO)
daysvec = c(mean_by_v3_pred$Time, mean_by_v3_observed$Time)
varvec = c(mean_by_v3_pred$FA, mean_by_v3_observed$FA)

v3df = data.frame(Status = statusvec, Time = daysvec, Mean = meanvec, SEL = meanvec - sevec, SEU = meanvec + sevec, Variable = varvec)
v3df$Time = factor(v3df$Time, levels = c("56", "112", "365"))
v3df =  v3df %>% filter(Variable %in% c("3", "2"))

ggplot(v3df, aes(x = Time, y = Mean, color = factor(Variable), linetype = Status)) +
  ylim(0, 0.2) +
  geom_point(aes(x = Time, y = Mean, color = factor(Variable))) +
  geom_line(aes(x = Time, y = Mean, color = factor(Variable), group = interaction(Variable, Status)), linewidth = 0.8) +
  scale_colour_manual(name = "Feeding", labels = c("No Cotrimoxazole", "Cotrimoxazole"),
                      breaks = c("3", "2"),
                      values = c("chartreuse3", "darkgreen")) +
  scale_linetype_manual(name = "Mean",
                        values = c("Observed" = "solid", "Predicted" = "dashed"),  # Define line types for each level of Status
                        labels = c("Observed" = "Empirical", "Predicted" = "Conditional (GLMM Prediction)")) +  # Set custom labels
  #values = c("Control" = "darkslategrey", "MVA85A" = "firebrick")) +  # Adjust colors for clarity
  theme_bw() + xlab("\n Time (Days After Birth)") + ylab(paste0("Mean ", varA[6], " \n")) + labs(title = "") + 
  theme(axis.title.x = element_text(size = 12, family = "Arial", face = "bold"),
        axis.title.y = element_text(size = 12, family = "Arial", face = "bold"),
        axis.text.x = element_text(size = 10, family = "Arial"),
        axis.text.y = element_text(size = 10, family = "Arial"),
        legend.text = element_text(size = 10, family = "Arial"),
        legend.position = "bottom")

# LQMM

AM_2.1 = lqmm(fixed = O6 ~ Treatment*Time + Gender*Time, random = ~ 1, tau = 0.5, na.action = na.omit, group = ID, data = groupA, nK = 1, type = "normal")
AS_2.1 = summary(AM_2.1)

R2.1 = ranef(AM_2.1)
qqnorm(R2.1$`(Intercept)`, main = "")
qqline(R2.1$`(Intercept)`)


AM_2.2 = lqmm(fixed = O6 ~ QFT*Time + Gender*Time, random = ~ 1, tau = 0.5, na.action = na.omit, group = ID, data = groupA, nK = 1, type = "normal")
AS_2.2 = summary(AM_2.2)

R2.2 = ranef(AM_2.2)
qqnorm(R2.2$`(Intercept)`, main = "")
qqline(R2.2$`(Intercept)`)

AM_2.3 = lqmm(fixed = O6 ~ FA*Time + Gender*Time, random = ~ 1, tau = 0.5, na.action = na.omit, group = ID, data = groupA, nK = 1, type = "normal")
AS_2.3 = summary(AM_2.3)

R2.3 = ranef(AM_2.3)
qqnorm(R2.3$`(Intercept)`, main = "")
qqline(R2.3$`(Intercept)`)

```

**Bulk CD4+/% R7+RA+:**: 
```{r Outcome15, include=TRUE}
l = varA[15]
k = 15

# Fit models

# LMM

AM_0.1 = glmmTMB(94 - O15 ~ Treatment*Time + Gender*Time + (1| ID), data = groupA, family = gaussian(link = "identity"))
AS_0.1 = summary(AM_0.1)

R0.1 = ranef(AM_0.1)
qqnorm(R0.1$cond$ID$`(Intercept)`, main = "")
qqline(R0.1$cond$ID$`(Intercept)`)

Rs0.1 = residuals(AM_0.1, type = "response")
qqnorm(Rs0.1, main = "")
qqline(Rs0.1)


AM_0.2 = glmmTMB(94 - O15 ~ QFT*Time + Gender*Time + (1| ID), data = groupA, family = gaussian(link = "identity"))
AS_0.2 = summary(AM_0.2)

R0.2 = ranef(AM_0.2)
qqnorm(R0.2$cond$ID$`(Intercept)`, main = "")
qqline(R0.2$cond$ID$`(Intercept)`)

Rs0.2 = residuals(AM_0.2, type = "response")
qqnorm(Rs0.2, main = "")
qqline(Rs0.2)

# Formula, antibiotic is ref for breastfeeding, antibiotic (3)
# Formula, antibiotic is ref for formula, no antibiotic (1)

AM_0.3 = glmmTMB(94 - O15 ~ FA*Time + Gender*Time + (1| ID), data = groupA, family = gaussian(link = "identity"))
AS_0.3 = summary(AM_0.3)

R0.3 = ranef(AM_0.3)
qqnorm(R0.3$cond$ID$`(Intercept)`, main = "")
qqline(R0.3$cond$ID$`(Intercept)`)

Rs0.3 = residuals(AM_0.3, type = "response")
qqnorm(Rs0.3, main = "")
qqline(Rs0.3)

# GLMM

AM_1.1 = glmmTMB(94 - O15 ~ Treatment*Time + Gender*Time + (1| ID), data = groupA, family = tweedie(link = "log"))
AS_1.1 = summary(AM_1.1)

R1.1 = ranef(AM_1.1)
qqnorm(R1.1$cond$ID$`(Intercept)`, main = "")
qqline(R1.1$cond$ID$`(Intercept)`)

plot(simulateResiduals(AM_1.1, n = 1000))

# Treatment

pred_v1frame = AM_1.1$frame

pred_v1 = predict(AM_1.1, type = "cond")
pred_v1dat = data.frame(ID = pred_v1frame$ID, Time = as.character(pred_v1frame$Time), 
                        MVA85A = as.character(pred_v1frame$Treatment),
                        Sex = as.character(pred_v1frame$Gender), O = 94 - pred_v1frame$`94 - O15`, P = 94 - pred_v1)


mean_by_v1_pred = pred_v1dat %>% group_by(Time, MVA85A) %>%
  summarise(meanP = mean(P, na.rm = TRUE), seP = 0, .groups = 'drop')
mean_by_v1_observed = pred_v1dat %>% group_by(Time, MVA85A) %>%
  summarise(meanO = mean(O, na.rm = TRUE), seO = sd(O) / sqrt(n()), .groups = 'drop')

mean_by_v1_predG = pred_v1dat %>% group_by(Time, Sex, MVA85A) %>%
  summarise(meanP = mean(P, na.rm = TRUE), seP = 0, .groups = 'drop')
mean_by_v1_observedG = pred_v1dat %>% group_by(Time, Sex, MVA85A) %>%
  summarise(meanO = mean(O, na.rm = TRUE), seO = sd(O) / sqrt(n()), .groups = 'drop')


meanvec = c(mean_by_v1_pred$meanP, mean_by_v1_observed$meanO)
statusvec = c(rep("Predicted", 6), rep("Observed", 6))
sevec = c(mean_by_v1_pred$seP, mean_by_v1_observed$seO)
daysvec = c(mean_by_v1_pred$Time, mean_by_v1_observed$Time)
varvec = c(mean_by_v1_pred$MVA85A, mean_by_v1_observed$MVA85A)

v1df = data.frame(Status = statusvec, Time = daysvec, Mean = meanvec, SEL = meanvec - sevec, SEU = meanvec + sevec, Variable = varvec)
v1df$Time = factor(v1df$Time, levels = c("56", "112", "365"))

ggplot(v1df, aes(x = Time, y = Mean, color = factor(Variable), linetype = Status)) +
  ylim(50, 100) +
  geom_point(aes(x = Time, y = Mean, color = factor(Variable))) +
  geom_line(aes(x = Time, y = Mean, color = factor(Variable), group = interaction(Variable, Status)), linewidth = 0.8) +
  scale_colour_manual(name = "Priming", labels = c("Control", "MVA85A"),
                      breaks = c("Control", "MVA85A"),
                      values = c("orange", "firebrick")) +
  scale_linetype_manual(name = "Mean",
                        values = c("Observed" = "solid", "Predicted" = "dashed"),  # Define line types for each level of Status
                        labels = c("Observed" = "Empirical", "Predicted" = "Conditional (GLMM Prediction)")) +  # Set custom labels
  #values = c("Control" = "darkslategrey", "MVA85A" = "firebrick")) +  # Adjust colors for clarity
  theme_bw() + xlab("\n Time (Days After Birth)") + ylab(paste0("Mean ", varA[15], " \n")) + labs(title = "") + 
  theme(axis.title.x = element_text(size = 12, family = "Arial", face = "bold"),
        axis.title.y = element_text(size = 12, family = "Arial", face = "bold"),
        axis.text.x = element_text(size = 10, family = "Arial"),
        axis.text.y = element_text(size = 10, family = "Arial"),
        legend.text = element_text(size = 10, family = "Arial"),
        legend.position = "bottom")



AM_1.2 = glmmTMB(94 - O15 ~ QFT*Time + Gender*Time + (1| ID), data = groupA, family = tweedie(link = "log"))
AS_1.2 = summary(AM_1.2)

R1.2 = ranef(AM_1.2)
qqnorm(R1.2$cond$ID$`(Intercept)`, main = "")
qqline(R1.2$cond$ID$`(Intercept)`)

plot(simulateResiduals(AM_1.2, n = 1000))

pred_v2frame = AM_1.2$frame

pred_v2 = predict(AM_1.2, type = "cond")
pred_v2dat = data.frame(ID = pred_v2frame$ID, Time = as.character(pred_v2frame$Time), 
                        QFT = as.character(pred_v2frame$QFT),
                        Sex = as.character(pred_v2frame$Gender), O = 94 - pred_v2frame$`94 - O15`, P = 94 - pred_v2)


mean_by_v2_pred = pred_v2dat %>% group_by(Time, QFT) %>%
  summarise(meanP = mean(P, na.rm = TRUE), seP = 0, .groups = 'drop')
mean_by_v2_observed = pred_v2dat %>% group_by(Time, QFT) %>%
  summarise(meanO = mean(O, na.rm = TRUE), seO = sd(O) / sqrt(n()), .groups = 'drop')

mean_by_v2_predG = pred_v2dat %>% group_by(Time, Sex, QFT) %>%
  summarise(meanP = mean(P, na.rm = TRUE), seP = 0, .groups = 'drop')
mean_by_v2_observedG = pred_v2dat %>% group_by(Time, Sex, QFT) %>%
  summarise(meanO = mean(O, na.rm = TRUE), seO = sd(O) / sqrt(n()), .groups = 'drop')


meanvec = c(mean_by_v2_pred$meanP, mean_by_v2_observed$meanO)
statusvec = c(rep("Predicted", 6), rep("Observed", 6))
sevec = c(mean_by_v2_pred$seP, mean_by_v2_observed$seO)
daysvec = c(mean_by_v2_pred$Time, mean_by_v2_observed$Time)
varvec = c(mean_by_v2_pred$QFT, mean_by_v2_observed$QFT)

v2df = data.frame(Status = statusvec, Time = daysvec, Mean = meanvec, SEL = meanvec - sevec, SEU = meanvec + sevec, Variable = varvec)
v2df$Time = factor(v2df$Time, levels = c("56", "112", "365"))

ggplot(v2df, aes(x = Time, y = Mean, color = factor(Variable), linetype = Status)) +
  ylim(50, 100) +
  geom_point(aes(x = Time, y = Mean, color = factor(Variable))) +
  geom_line(aes(x = Time, y = Mean, color = factor(Variable), group = interaction(Variable, Status)), linewidth = 0.8) +
  scale_colour_manual(name = "Maternal QFT", labels = c("Negative", "Positive"),
                      breaks = c("Negative", "Positive"),
                      values = c("darkcyan", "darkblue")) +
  scale_linetype_manual(name = "Mean",
                        values = c("Observed" = "solid", "Predicted" = "dashed"),  # Define line types for each level of Status
                        labels = c("Observed" = "Empirical", "Predicted" = "Conditional (GLMM Prediction)")) +  # Set custom labels
  #values = c("Control" = "darkslategrey", "MVA85A" = "firebrick")) +  # Adjust colors for clarity
  theme_bw() + xlab("\n Time (Days After Birth)") + ylab(paste0("Mean ", varA[15], " \n")) + labs(title = "") + 
  theme(axis.title.x = element_text(size = 12, family = "Arial", face = "bold"),
        axis.title.y = element_text(size = 12, family = "Arial", face = "bold"),
        axis.text.x = element_text(size = 10, family = "Arial"),
        axis.text.y = element_text(size = 10, family = "Arial"),
        legend.text = element_text(size = 10, family = "Arial"),
        legend.position = "bottom")



AM_1.3 = glmmTMB(94 - O15 ~ FA*Time + Gender*Time + (1| ID), data = groupA, family = tweedie(link = "log"))
AS_1.3 = summary(AM_1.3)

R1.3 = ranef(AM_1.3)
qqnorm(R1.3$cond$ID$`(Intercept)`, main = "")
qqline(R1.3$cond$ID$`(Intercept)`)

plot(simulateResiduals(AM_1.3, n = 1000))

# FA

pred_v3frame = AM_1.3$frame

pred_v3 = predict(AM_1.3, type = "cond")
pred_v3dat = data.frame(ID = pred_v3frame$ID, Time = as.character(pred_v3frame$Time), 
                        FA = as.character(pred_v3frame$FA),
                        Sex = as.character(pred_v3frame$Gender), O = 94 - pred_v3frame$`94 - O15`, P = 94 - pred_v3)


mean_by_v3_pred = pred_v3dat %>% group_by(Time, FA) %>%
  summarise(meanP = mean(P, na.rm = TRUE), seP = 0, .groups = 'drop')
mean_by_v3_observed = pred_v3dat %>% group_by(Time, FA) %>%
  summarise(meanO = mean(O, na.rm = TRUE), seO = sd(O) / sqrt(n()), .groups = 'drop')

mean_by_v3_predG = pred_v3dat %>% group_by(Time, Sex, FA) %>%
  summarise(meanP = mean(P, na.rm = TRUE), seP = 0, .groups = 'drop')
mean_by_v3_observedG = pred_v3dat %>% group_by(Time, Sex, FA) %>%
  summarise(meanO = mean(O, na.rm = TRUE), seO = sd(O) / sqrt(n()), .groups = 'drop')


meanvec = c(mean_by_v3_pred$meanP, mean_by_v3_observed$meanO)
statusvec = c(rep("Predicted", 12), rep("Observed", 12))
sevec = c(mean_by_v3_pred$seP, mean_by_v3_observed$seO)
daysvec = c(mean_by_v3_pred$Time, mean_by_v3_observed$Time)
varvec = c(mean_by_v3_pred$FA, mean_by_v3_observed$FA)

v3df = data.frame(Status = statusvec, Time = daysvec, Mean = meanvec, SEL = meanvec - sevec, SEU = meanvec + sevec, Variable = varvec)
v3df$Time = factor(v3df$Time, levels = c("56", "112", "365"))
v3df =  v3df %>% filter(Variable %in% c("3", "2"))

ggplot(v3df, aes(x = Time, y = Mean, color = factor(Variable), linetype = Status)) +
  ylim(50, 100) +
  geom_point(aes(x = Time, y = Mean, color = factor(Variable))) +
  geom_line(aes(x = Time, y = Mean, color = factor(Variable), group = interaction(Variable, Status)), linewidth = 0.8) +
  scale_colour_manual(name = "Feeding", labels = c("No Cotrimoxazole", "Cotrimoxazole"),
                      breaks = c("3", "2"),
                      values = c("chartreuse3", "darkgreen")) +
  scale_linetype_manual(name = "Mean",
                        values = c("Observed" = "solid", "Predicted" = "dashed"),  # Define line types for each level of Status
                        labels = c("Observed" = "Empirical", "Predicted" = "Conditional (GLMM Prediction)")) +  # Set custom labels
  #values = c("Control" = "darkslategrey", "MVA85A" = "firebrick")) +  # Adjust colors for clarity
  theme_bw() + xlab("\n Time (Days After Birth)") + ylab(paste0("Mean ", varA[15], " \n")) + labs(title = "") + 
  theme(axis.title.x = element_text(size = 12, family = "Arial", face = "bold"),
        axis.title.y = element_text(size = 12, family = "Arial", face = "bold"),
        axis.text.x = element_text(size = 10, family = "Arial"),
        axis.text.y = element_text(size = 10, family = "Arial"),
        legend.text = element_text(size = 10, family = "Arial"),
        legend.position = "bottom")

# LQMM


# LQMM

AM_2.1 = lqmm(fixed = 94 - O15 ~ Treatment*Time + Gender*Time, random = ~ 1, tau = 0.5, na.action = na.omit, group = ID, data = groupA, nK = 1, type = "normal")
AS_2.1 = summary(AM_2.1)

R2.1 = ranef(AM_2.1)
qqnorm(R2.1$`(Intercept)`, main = "")
qqline(R2.1$`(Intercept)`)


AM_2.2 = lqmm(fixed = 94 - O15 ~ QFT*Time + Gender*Time, random = ~ 1, tau = 0.5, na.action = na.omit, group = ID, data = groupA, nK = 1, type = "normal")
AS_2.2 = summary(AM_2.2)

R2.2 = ranef(AM_2.2)
qqnorm(R2.2$`(Intercept)`, main = "")
qqline(R2.2$`(Intercept)`)

AM_2.3 = lqmm(fixed = 94 - O15 ~ FA*Time + Gender*Time, random = ~ 1, tau = 0.5, na.action = na.omit, group = ID, data = groupA, nK = 1, type = "normal")
AS_2.3 = summary(AM_2.3)

R2.3 = ranef(AM_2.3)
qqnorm(R2.3$`(Intercept)`, main = "")
qqline(R2.3$`(Intercept)`)


```

**GrK+ %of Ki67+ NK:** 

```{r Outcome39, include=TRUE}
l = varA[39]
k = 39

# Fit models

# LMM

AM_0.1 = glmmTMB(O39 ~ Treatment*Time + Gender*Time + (1| ID), data = groupA, family = gaussian(link = "identity"))
AS_0.1 = summary(AM_0.1)

R0.1 = ranef(AM_0.1)
qqnorm(R0.1$cond$ID$`(Intercept)`, main = "")
qqline(R0.1$cond$ID$`(Intercept)`)

Rs0.1 = residuals(AM_0.1, type = "response")
qqnorm(Rs0.1, main = "")
qqline(Rs0.1)


AM_0.2 = glmmTMB(O39 ~ QFT*Time + Gender*Time + (1| ID), data = groupA, family = gaussian(link = "identity"))
AS_0.2 = summary(AM_0.2)

R0.2 = ranef(AM_0.2)
qqnorm(R0.2$cond$ID$`(Intercept)`, main = "")
qqline(R0.2$cond$ID$`(Intercept)`)

Rs0.2 = residuals(AM_0.2, type = "response")
qqnorm(Rs0.2, main = "")
qqline(Rs0.2)

# Formula, antibiotic is ref for breastfeeding, antibiotic (3)
# Formula, antibiotic is ref for formula, no antibiotic (1)

AM_0.3 = glmmTMB(O39 ~ FA*Time + Gender*Time + (1| ID), data = groupA, family = gaussian(link = "identity"))
AS_0.3 = summary(AM_0.3)

R0.3 = ranef(AM_0.3)
qqnorm(R0.3$cond$ID$`(Intercept)`, main = "")
qqline(R0.3$cond$ID$`(Intercept)`)

Rs0.3 = residuals(AM_0.3, type = "response")
qqnorm(Rs0.3, main = "")
qqline(Rs0.3)

# GLMM

AM_1.1 = glmmTMB(O39 ~ Treatment*Time + Gender*Time + (1| ID), data = groupA, family = tweedie(link = "log"))
AS_1.1 = summary(AM_1.1)

R1.1 = ranef(AM_1.1)
qqnorm(R1.1$cond$ID$`(Intercept)`, main = "")
qqline(R1.1$cond$ID$`(Intercept)`)

plot(simulateResiduals(AM_1.1, n = 1000))

# Treatment

pred_v1frame = AM_1.1$frame

pred_v1 = predict(AM_1.1, type = "cond")
pred_v1dat = data.frame(ID = pred_v1frame$ID, Time = as.character(pred_v1frame$Time), 
                        MVA85A = as.character(pred_v1frame$Treatment),
                        Sex = as.character(pred_v1frame$Gender), O = pred_v1frame$O39, P = pred_v1)


mean_by_v1_pred = pred_v1dat %>% group_by(Time, MVA85A) %>%
  summarise(meanP = mean(P, na.rm = TRUE), seP = 0, .groups = 'drop')
mean_by_v1_observed = pred_v1dat %>% group_by(Time, MVA85A) %>%
  summarise(meanO = mean(O, na.rm = TRUE), seO = sd(O) / sqrt(n()), .groups = 'drop')

mean_by_v1_predG = pred_v1dat %>% group_by(Time, Sex, MVA85A) %>%
  summarise(meanP = mean(P, na.rm = TRUE), seP = 0, .groups = 'drop')
mean_by_v1_observedG = pred_v1dat %>% group_by(Time, Sex, MVA85A) %>%
  summarise(meanO = mean(O, na.rm = TRUE), seO = sd(O) / sqrt(n()), .groups = 'drop')


meanvec = c(mean_by_v1_pred$meanP, mean_by_v1_observed$meanO)
statusvec = c(rep("Predicted", 6), rep("Observed", 6))
sevec = c(mean_by_v1_pred$seP, mean_by_v1_observed$seO)
daysvec = c(mean_by_v1_pred$Time, mean_by_v1_observed$Time)
varvec = c(mean_by_v1_pred$MVA85A, mean_by_v1_observed$MVA85A)

v1df = data.frame(Status = statusvec, Time = daysvec, Mean = meanvec, SEL = meanvec - sevec, SEU = meanvec + sevec, Variable = varvec)
v1df$Time = factor(v1df$Time, levels = c("56", "112", "365"))

ggplot(v1df, aes(x = Time, y = Mean, color = factor(Variable), linetype = Status)) +
  ylim(0, 100) +
  geom_point(aes(x = Time, y = Mean, color = factor(Variable))) +
  geom_line(aes(x = Time, y = Mean, color = factor(Variable), group = interaction(Variable, Status)), linewidth = 0.8) +
  scale_colour_manual(name = "Priming", labels = c("Control", "MVA85A"),
                      breaks = c("Control", "MVA85A"),
                      values = c("orange", "firebrick")) +
  scale_linetype_manual(name = "Mean",
                        values = c("Observed" = "solid", "Predicted" = "dashed"),  # Define line types for each level of Status
                        labels = c("Observed" = "Empirical", "Predicted" = "Conditional (GLMM Prediction)")) +  # Set custom labels
  #values = c("Control" = "darkslategrey", "MVA85A" = "firebrick")) +  # Adjust colors for clarity
  theme_bw() + xlab("\n Time (Days After Birth)") + ylab(paste0("Mean ", varA[39], " \n")) + labs(title = "") + 
  theme(axis.title.x = element_text(size = 12, family = "Arial", face = "bold"),
        axis.title.y = element_text(size = 12, family = "Arial", face = "bold"),
        axis.text.x = element_text(size = 10, family = "Arial"),
        axis.text.y = element_text(size = 10, family = "Arial"),
        legend.text = element_text(size = 10, family = "Arial"),
        legend.position = "bottom")


AM_1.2 = glmmTMB(O39 ~ QFT*Time + Gender*Time + (1| ID), data = groupA, family = tweedie(link = "log"))
AS_1.2 = summary(AM_1.2)

R1.2 = ranef(AM_1.2)
qqnorm(R1.2$cond$ID$`(Intercept)`, main = "")
qqline(R1.2$cond$ID$`(Intercept)`)

plot(simulateResiduals(AM_1.2, n = 1000))

pred_v2frame = AM_1.2$frame

pred_v2 = predict(AM_1.2, type = "cond")
pred_v2dat = data.frame(ID = pred_v2frame$ID, Time = as.character(pred_v2frame$Time), 
                        QFT = as.character(pred_v2frame$QFT),
                        Sex = as.character(pred_v2frame$Gender), O = pred_v2frame$O39, P = pred_v2)


mean_by_v2_pred = pred_v2dat %>% group_by(Time, QFT) %>%
  summarise(meanP = mean(P, na.rm = TRUE), seP = 0, .groups = 'drop')
mean_by_v2_observed = pred_v2dat %>% group_by(Time, QFT) %>%
  summarise(meanO = mean(O, na.rm = TRUE), seO = sd(O) / sqrt(n()), .groups = 'drop')

mean_by_v2_predG = pred_v2dat %>% group_by(Time, Sex, QFT) %>%
  summarise(meanP = mean(P, na.rm = TRUE), seP = 0, .groups = 'drop')
mean_by_v2_observedG = pred_v2dat %>% group_by(Time, Sex, QFT) %>%
  summarise(meanO = mean(O, na.rm = TRUE), seO = sd(O) / sqrt(n()), .groups = 'drop')


meanvec = c(mean_by_v2_pred$meanP, mean_by_v2_observed$meanO)
statusvec = c(rep("Predicted", 6), rep("Observed", 6))
sevec = c(mean_by_v2_pred$seP, mean_by_v2_observed$seO)
daysvec = c(mean_by_v2_pred$Time, mean_by_v2_observed$Time)
varvec = c(mean_by_v2_pred$QFT, mean_by_v2_observed$QFT)

v2df = data.frame(Status = statusvec, Time = daysvec, Mean = meanvec, SEL = meanvec - sevec, SEU = meanvec + sevec, Variable = varvec)
v2df$Time = factor(v2df$Time, levels = c("56", "112", "365"))

ggplot(v2df, aes(x = Time, y = Mean, color = factor(Variable), linetype = Status)) +
  ylim(0, 100) +
  geom_point(aes(x = Time, y = Mean, color = factor(Variable))) +
  geom_line(aes(x = Time, y = Mean, color = factor(Variable), group = interaction(Variable, Status)), linewidth = 0.8) +
  scale_colour_manual(name = "Maternal QFT", labels = c("Negative", "Positive"),
                      breaks = c("Negative", "Positive"),
                      values = c("darkcyan", "darkblue")) +
  scale_linetype_manual(name = "Mean",
                        values = c("Observed" = "solid", "Predicted" = "dashed"),  # Define line types for each level of Status
                        labels = c("Observed" = "Empirical", "Predicted" = "Conditional (GLMM Prediction)")) +  # Set custom labels
  #values = c("Control" = "darkslategrey", "MVA85A" = "firebrick")) +  # Adjust colors for clarity
  theme_bw() + xlab("\n Time (Days After Birth)") + ylab(paste0("Mean ", varA[39], " \n")) + labs(title = "") + 
  theme(axis.title.x = element_text(size = 12, family = "Arial", face = "bold"),
        axis.title.y = element_text(size = 12, family = "Arial", face = "bold"),
        axis.text.x = element_text(size = 10, family = "Arial"),
        axis.text.y = element_text(size = 10, family = "Arial"),
        legend.text = element_text(size = 10, family = "Arial"),
        legend.position = "bottom")

AM_1.3 = glmmTMB(O39 ~ FA*Time + Gender*Time + (1| ID), data = groupA, family = tweedie(link = "log"))
AS_1.3 = summary(AM_1.3)

R1.3 = ranef(AM_1.3)
qqnorm(R1.3$cond$ID$`(Intercept)`, main = "")
qqline(R1.3$cond$ID$`(Intercept)`)

plot(simulateResiduals(AM_1.3, n = 1000))

# FA

pred_v3frame = AM_1.3$frame

pred_v3 = predict(AM_1.3, type = "cond")
pred_v3dat = data.frame(ID = pred_v3frame$ID, Time = as.character(pred_v3frame$Time), 
                        FA = as.character(pred_v3frame$FA),
                        Sex = as.character(pred_v3frame$Gender), O = pred_v3frame$O39, P = pred_v3)


mean_by_v3_pred = pred_v3dat %>% group_by(Time, FA) %>%
  summarise(meanP = mean(P, na.rm = TRUE), seP = 0, .groups = 'drop')
mean_by_v3_observed = pred_v3dat %>% group_by(Time, FA) %>%
  summarise(meanO = mean(O, na.rm = TRUE), seO = sd(O) / sqrt(n()), .groups = 'drop')

mean_by_v3_predG = pred_v3dat %>% group_by(Time, Sex, FA) %>%
  summarise(meanP = mean(P, na.rm = TRUE), seP = 0, .groups = 'drop')
mean_by_v3_observedG = pred_v3dat %>% group_by(Time, Sex, FA) %>%
  summarise(meanO = mean(O, na.rm = TRUE), seO = sd(O) / sqrt(n()), .groups = 'drop')


meanvec = c(mean_by_v3_pred$meanP, mean_by_v3_observed$meanO)
statusvec = c(rep("Predicted", 12), rep("Observed", 12))
sevec = c(mean_by_v3_pred$seP, mean_by_v3_observed$seO)
daysvec = c(mean_by_v3_pred$Time, mean_by_v3_observed$Time)
varvec = c(mean_by_v3_pred$FA, mean_by_v3_observed$FA)

v3df = data.frame(Status = statusvec, Time = daysvec, Mean = meanvec, SEL = meanvec - sevec, SEU = meanvec + sevec, Variable = varvec)
v3df$Time = factor(v3df$Time, levels = c("56", "112", "365"))
v3df =  v3df %>% filter(Variable %in% c("3", "2"))

ggplot(v3df, aes(x = Time, y = Mean, color = factor(Variable), linetype = Status)) +
  ylim(0, 100) +
  geom_point(aes(x = Time, y = Mean, color = factor(Variable))) +
  geom_line(aes(x = Time, y = Mean, color = factor(Variable), group = interaction(Variable, Status)), linewidth = 0.8) +
  scale_colour_manual(name = "Feeding", labels = c("No Cotrimoxazole", "Cotrimoxazole"),
                      breaks = c("3", "2"),
                      values = c("chartreuse3", "darkgreen")) +
  scale_linetype_manual(name = "Mean",
                        values = c("Observed" = "solid", "Predicted" = "dashed"),  # Define line types for each level of Status
                        labels = c("Observed" = "Empirical", "Predicted" = "Conditional (GLMM Prediction)")) +  # Set custom labels
  #values = c("Control" = "darkslategrey", "MVA85A" = "firebrick")) +  # Adjust colors for clarity
  theme_bw() + xlab("\n Time (Days After Birth)") + ylab(paste0("Mean ", varA[39], " \n")) + labs(title = "") + 
  theme(axis.title.x = element_text(size = 12, family = "Arial", face = "bold"),
        axis.title.y = element_text(size = 12, family = "Arial", face = "bold"),
        axis.text.x = element_text(size = 10, family = "Arial"),
        axis.text.y = element_text(size = 10, family = "Arial"),
        legend.text = element_text(size = 10, family = "Arial"),
        legend.position = "bottom")

# LQMM

AM_2.1 = lqmm(fixed = O39 ~ Treatment*Time + Gender*Time, random = ~ 1, tau = 0.5, na.action = na.omit, group = ID, data = groupA, nK = 1, type = "normal")
AS_2.1 = summary(AM_2.1)

R2.1 = ranef(AM_2.1)
qqnorm(R2.1$`(Intercept)`, main = "")
qqline(R2.1$`(Intercept)`)

AM_2.2 = lqmm(fixed = O39 ~ QFT*Time + Gender*Time, random = ~ 1, tau = 0.5, na.action = na.omit, group = ID, data = groupA, nK = 1, type = "normal")
AS_2.2 = summary(AM_2.2)

R2.2 = ranef(AM_2.2)
qqnorm(R2.2$`(Intercept)`, main = "")
qqline(R2.2$`(Intercept)`)

AM_2.3 = lqmm(fixed = O39 ~ FA*Time + Gender*Time, random = ~ 1, tau = 0.5, na.action = na.omit, group = ID, data = groupA, nK = 1, type = "normal")
AS_2.3 = summary(AM_2.3)

R2.3 = ranef(AM_2.3)
qqnorm(R2.3$`(Intercept)`, main = "")
qqline(R2.3$`(Intercept)`)

```

